### ISSUE TITLE
Remove dependencies on mantidplot

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/fitbenchmarking#10]
Here get this tool to work from python mantid. this includes removing dependencies on mantidplot

**Comment by Anders-Markvardsen** [comment]
On e.g. windows should work to be able to do 

```
C:\MantidInstall\bin\mantidpython.bat fitbenchmarking/runScripts.py
```

note first versions of runScripts.py paths likely need updating

**Comment by AnthonyLim23** [comment]
https://github.com/mantidproject/fitbenchmarking/blob/master/fitbenchmarking/results_output.py#L30

**Comment by AnthonyLim23** [comment]
In [11]: run runScripts.py
FrameworkManager-[Notice] Welcome to Mantid 3.12.0
CheckMantidVersion-[Notice] A new version of Mantid(3.12.1) is available for download from http://download.mantidproject.org
Error in logging framework: Cannot open fileError in logging framework: Cannot open fileError in logging framework: Cannot open fileDownloadInstrument-[Notice] All instrument definitions up to date
Error in logging framework: Cannot open filePython-[Warning] Failed to load plugin C:/Users/BTR75544/Desktop/GUI_TEST/algs/MaxentStressTester2.py. Error: name 'SetupSimInstrument' is not defined
Error in logging framework: Cannot open filePython-[Warning] Failed to load plugin C:/Users/BTR75544/Desktop/GUI_TEST/algs/phaseTable.py. Error: name 'CreateEmptyTableWorkspace' is not defined
Error in logging framework: Cannot open filePython-[Warning] Failed to load plugin C:/Users/BTR75544/Desktop/GUI_TEST/algs/testmultiFunc.py. Error: name 'CreateWorkspace' is not defined
Error in logging framework: Cannot open file[ 0.+0.j  1.+2.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j
  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
swapping 1  with  4
swapping 2  with  4
swapping 3  with  4
(1+2j)
(0.158512667781+2.23044249739j)
(-0.707106781187+2.12132034356j)
(-1.46507563266+1.68924639724j)
(-2+1j)
(-2.23044249739+0.158512667781j)
(-2.12132034356-0.707106781187j)
(-1.68924639724-1.46507563266j)
(-1-2j)
(-0.158512667781-2.23044249739j)
(0.707106781187-2.12132034356j)
(1.46507563266-1.68924639724j)
(2-1j)
(2.23044249739-0.158512667781j)
(2.12132034356+0.707106781187j)
(1.68924639724+1.46507563266j)
[ 1.+2.j -2.+1.j -1.-2.j  2.-1.j  1.+2.j -2.+1.j -1.-2.j  2.-1.j  0.+0.j
  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
Python-[Warning] Failed to load plugin C:/Users/BTR75544/Desktop/GUI_TEST/algs/OpengenieMaxentTools\output.py. Error: invalid syntax (output.py, line 77)
Error in logging framework: Cannot open filePython-[Warning] Failed to load plugin C:/Users/BTR75544/Desktop/GUI_TEST/algs/OpengenieMaxentTools\read.py. Error: invalid syntax (read.py, line 452)
Error in logging framework: Cannot open fileFound test problem files:  []



********************************************************
**************** RESULTS FOR GROUP 1, NIST, "lower" difficulty ************
********************************************************
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
C:\Users\BTR75544\work\fitBench\fitBench\fitbenchmarking\fitbenchmarking\runScripts.py in <module>()
     62                                           group_name=group_suffix_names[idx],
     63                                           use_errors=use_errors,
---> 64                                           simple_text=True, rst=True, save_to_file=True, color_scale=color_scale)
     65
     66

C:\Users\BTR75544\work\fitBench\fitBench\fitbenchmarking\fitbenchmarking\results_output.py in print_group_results_tables(minimizers, results_per_test, problems_obj, group_name, use_errors, simple_text, rst, save_to_file, color_scale)
     76     accuracy_tbl, runtime_tbl = postproc.calc_accuracy_runtime_tbls(results_per_test, minimizers)
     77     norm_acc_rankings, norm_runtimes, summary_cells_acc, summary_cells_runtime = \
---> 78         postproc.calc_norm_summary_tables(accuracy_tbl, runtime_tbl)
     79
     80     if simple_text:

C:\Users\BTR75544\work\fitBench\fitBench\fitbenchmarking\fitbenchmarking\post_processing.py in calc_norm_summary_tables(accuracy_tbl, time_tbl)
    109     norm_runtimes = time_tbl / min_runtime[:, None]
    110
--> 111     summary_cells_acc = np.array([np.nanmin(norm_acc_rankings, 0),
    112                                   np.nanmax(norm_acc_rankings, 0),
    113                                   nanmean(norm_acc_rankings, 0),

C:\Users\BTR75544\nightly\MantidInstall\bin\lib\site-packages\numpy\lib\nanfunctions.pyc in nanmin(a, axis, out, keepdims)
    216     if not isinstance(a, np.ndarray) or type(a) is np.ndarray:
    217         # Fast, but not safe for subclasses of ndarray
--> 218         res = np.fmin.reduce(a, axis=axis, out=out, keepdims=keepdims)
    219         if np.isnan(res).any():
    220             warnings.warn("All-NaN axis encountered", RuntimeWarning)

ValueError: zero-size array to reduction operation fmin which has no identity

**Comment by Anders-Markvardsen** [comment]
yes probably needs a little bit of adjusting:)

**Comment by AnthonyLim23** [comment]
the problem is the file paths. I am tempted to move the run script to the main folder

**Comment by Anders-Markvardsen** [comment]
In terms of python packages it is recommended to have source is in that folder, e.g. see http://www.patricksoftwareblog.com/structure-of-a-python-project/  and http://docs.python-guide.org/en/latest/writing/structure/. However, within that folder don't hesitate to create sub-packages (sub folders).

**Comment by Anders-Markvardsen** [comment]
You are right about the hashed files. Please could you overwrite these with non-hashed versions
