### ISSUE TITLE
Renaming FittingTestProblem -> FittingProblem and similar changes

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/fitbenchmarking#125]
As discussed.

Rename classes
* FittingTestProblem -> FittingProblem
* FittingTestResult -> FittingResult

Rename files
* test_problem -> fitting_problem
* test_result -> fitting_result

Remember to also update: .coveragerc

**Comment by bb511** [comment]
This issue was solved in PR #143
