### ISSUE TITLE
Investigation into redesign of FittingProblem class

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/fitbenchmarking#154]
Investigation into redesign of FittingProblem and surrounding helper functions. 

Create diagrams docs and discuss these

* look into making helping functions member functions
* look into making FittingProblem a composite class

**Comment by Anders-Markvardsen** [comment]
@wathen please could you list the name of the helper functions you suggest can become member functions?

**Comment by wathen** [comment]
All the helper functions in  fitbenchmarking/fitbenchmarking/parsing/parse_data.py would need to go into the data class. Is this what you mean?

**Comment by Anders-Markvardsen** [comment]
Probably, thanks. I have block out time in my calendar to look at this tomorrow

**Comment by Anders-Markvardsen** [comment]
Notice that parse_data.py does not refer to a file in the master branch, does parse_data.py have an equivalent in master?

**Comment by wathen** [comment]
> Notice that parse_data.py does not refer to a file in the master branch, does parse_data.py have an equivalent in master?

**Comment by wathen** [comment]
> Notice that parse_data.py does not refer to a file in the master branch, does parse_data.py have an equivalent in master?

I merged parse_nist.py and parse_neutron.py into parse_data.py

**Comment by Anders-Markvardsen** [comment]
Taking as starting point branch from #139 then package structure of concern includes:

![image](https://user-images.githubusercontent.com/1135476/54992384-10bde280-4fb7-11e9-94f6-b21e10435970.png)

and the main class of attention here:

![image](https://user-images.githubusercontent.com/1135476/54992458-3fd45400-4fb7-11e9-84fd-8d56ed0fa186.png)

I agree with you @wathen on the added value of some reengineering here. 

@wathen how would you suggest functions in parsing could be better distributed as method and otherwise?
