### ISSUE TITLE
Code cleanup - remove unnecessary workspace creation 

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/fitbenchmarking#34]
When using neutron data, the workspace containing the data for the test problem is loaded at 
https://github.com/mantidproject/fitbenchmarking/blob/6286fce2b2daa9dfd0916297cb19d4df31daa55f/fitbenchmarking/input_parsing.py#L294-L300
Then an additional workspace is created later on:
https://github.com/mantidproject/fitbenchmarking/blob/6286fce2b2daa9dfd0916297cb19d4df31daa55f/fitbenchmarking/fitting_benchmarking.py#L348-L350
Ideally, when the workspace is loaded, one would want to avoid creating one such that the script is more efficient.

**Comment by bb511** [comment]
Upon further investigation, the code would need major restructuring. In solving this inefficiency, the code would only get more convoluted. It is worth tackling only if it will represent a bigger issue in the future.
