### ISSUE TITLE
Capture stdout from mantid functions and save it in the logging files

### ISSUE THREAD

**Issue by bb511** [mantidproject/fitbenchmarking#67]
After #58 , should capture the output of the mantid functions and pipe them in one of the logging files such that the terminal won't be so cluttered.

**Comment by bb511** [comment]
@Anders-Markvardsen Any idea how to capture this output (i.e. what the function, e.g. msapi.Fit outputs to the terminal)? Conventional methods do not work unfortunately.

**Comment by Anders-Markvardsen** [comment]
This may not be quite what we want, but see line 32 of https://github.com/ISISScientificComputing/autoreduce/blob/master/QueueProcessors/AutoreductionProcessor/post_process_admin.py for a python method designed to separate stdout and stderr

**Comment by bb511** [comment]
Ah, I tried using contextmanager, unfortunately that does not work.

**Comment by bb511** [comment]
This is not doable at the moment (according to Martyn). @Anders-Markvardsen
