### ISSUE TITLE
Enable Travis automatic testing

### ISSUE THREAD

**Issue by bb511** [mantidproject/fitbenchmarking#86]
On this repository, set up Travis such that a set of tests are applied whenever a pull request is submitted.

**Comment by AnthonyLim23** [comment]
https://travis-ci.org/

Elliot's powerpoint https://docs.google.com/presentation/d/1DpZ0tRCjbnO8hAiusOLoKOK-4IfS0mMp_jwAgXgIStw/edit

here is the mantid install script we use in autoreduction (note that it requires sudo access and installs to default `/opt/Mantid/`) https://github.com/ISISScientificComputing/autoreduce/blob/develop/build/install/mantid.sh
